import { solvedCube, type Color, type CubeFacelets, type Face, type NextStepCube } from './state';

const CUBIE_CORNERS: ReadonlyArray<readonly [number, number, number]> = [
  [-1, -1, -1],
  [+1, -1, -1],
  [-1, +1, -1],
  [+1, +1, -1],
  [-1, -1, +1],
  [+1, -1, +1],
  [-1, +1, +1],
  [+1, +1, +1],
];

const FACELET_TO_CUBIE: Record<Face, readonly [number, number, number, number]> = {
  U: [2, 3, 6, 7],
  D: [4, 5, 0, 1],
  F: [6, 7, 4, 5],
  B: [3, 2, 1, 0],
  L: [2, 6, 0, 4],
  R: [7, 3, 5, 1],
};

const FACE_LAYER_CUBIES: Record<Face, readonly number[]> = {
  U: [2, 3, 6, 7],
  D: [0, 1, 4, 5],
  F: [4, 5, 6, 7],
  B: [0, 1, 2, 3],
  L: [0, 2, 4, 6],
  R: [1, 3, 5, 7],
};

const FACE_OUTWARD_AXIS: Record<Face, readonly [number, number, number]> = {
  U: [0, 1, 0],
  D: [0, -1, 0],
  F: [0, 0, 1],
  B: [0, 0, -1],
  L: [-1, 0, 0],
  R: [1, 0, 0],
};

const FACES: ReadonlyArray<Face> = ['U', 'D', 'F', 'B', 'L', 'R'];
const FACE_INDEX: Record<Face, number> = { U: 0, D: 1, F: 2, B: 3, L: 4, R: 5 };

function faceForUnitAxis(x: number, y: number, z: number): Face {
  if (x === 1) return 'R';
  if (x === -1) return 'L';
  if (y === 1) return 'U';
  if (y === -1) return 'D';
  if (z === 1) return 'F';
  return 'B';
}

function cubieIndexAt(sx: number, sy: number, sz: number): number {
  return ((sx + 1) >> 1) | (((sy + 1) >> 1) << 1) | (((sz + 1) >> 1) << 2);
}

function stickerIndex(cubieIdx: number, x: number, y: number, z: number): number {
  const face = faceForUnitAxis(x, y, z);
  return FACE_INDEX[face] * 4 + FACELET_TO_CUBIE[face].indexOf(cubieIdx);
}

function rotate(
  x: number,
  y: number,
  z: number,
  kx: number,
  ky: number,
  kz: number,
  angle: number,
): [number, number, number] {
  const cosA = Math.cos(angle);
  const sinA = Math.sin(angle);
  const dot = x * kx + y * ky + z * kz;
  const cx = ky * z - kz * y;
  const cy = kz * x - kx * z;
  const cz = kx * y - ky * x;
  return [
    x * cosA + cx * sinA + kx * dot * (1 - cosA),
    y * cosA + cy * sinA + ky * dot * (1 - cosA),
    z * cosA + cz * sinA + kz * dot * (1 - cosA),
  ];
}

function buildWholeCubeRotation(
  ax: number,
  ay: number,
  az: number,
  angle: number,
): number[] {
  // Like buildBaseFacePermutation but rotates ALL 8 cubies (whole-cube rotation),
  // not just the cubies of one face's layer.
  const perm: number[] = new Array(24);
  for (let i = 0; i < 24; i++) perm[i] = i;

  for (let cubieIdx = 0; cubieIdx < 8; cubieIdx++) {
    const [sx, sy, sz] = CUBIE_CORNERS[cubieIdx];
    const [npx, npy, npz] = rotate(sx, sy, sz, ax, ay, az, angle);
    const newCubieIdx = cubieIndexAt(Math.round(npx), Math.round(npy), Math.round(npz));

    const stickerDirs: ReadonlyArray<readonly [number, number, number]> = [
      [sx, 0, 0],
      [0, sy, 0],
      [0, 0, sz],
    ];
    for (const [dx, dy, dz] of stickerDirs) {
      const oldIdx = stickerIndex(cubieIdx, dx, dy, dz);
      const [nx, ny, nz] = rotate(dx, dy, dz, ax, ay, az, angle);
      const newIdx = stickerIndex(newCubieIdx, Math.round(nx), Math.round(ny), Math.round(nz));
      perm[newIdx] = oldIdx;
    }
  }
  return perm;
}

function buildBaseFacePermutation(face: Face): number[] {
  const perm: number[] = new Array(24);
  for (let i = 0; i < 24; i++) perm[i] = i;

  const [ax, ay, az] = FACE_OUTWARD_AXIS[face];
  const angle = -Math.PI / 2; // CW from outside = right-hand-rule negative around outward axis

  for (const cubieIdx of FACE_LAYER_CUBIES[face]) {
    const [sx, sy, sz] = CUBIE_CORNERS[cubieIdx];
    const [npx, npy, npz] = rotate(sx, sy, sz, ax, ay, az, angle);
    const newCubieIdx = cubieIndexAt(Math.round(npx), Math.round(npy), Math.round(npz));

    const stickerDirs: ReadonlyArray<readonly [number, number, number]> = [
      [sx, 0, 0],
      [0, sy, 0],
      [0, 0, sz],
    ];
    for (const [dx, dy, dz] of stickerDirs) {
      const oldIdx = stickerIndex(cubieIdx, dx, dy, dz);
      const [nx, ny, nz] = rotate(dx, dy, dz, ax, ay, az, angle);
      const newIdx = stickerIndex(newCubieIdx, Math.round(nx), Math.round(ny), Math.round(nz));
      perm[newIdx] = oldIdx;
    }
  }
  return perm;
}

function composePerms(first: number[], second: number[]): number[] {
  // Apply `first` then `second`: result[i] = first[second[i]] applied to initial state.
  const out = new Array<number>(24);
  for (let i = 0; i < 24; i++) out[i] = first[second[i]];
  return out;
}

interface MoveDef {
  name: string;
  perm: number[];
}

// The 24 whole-cube rotations of a cube, as permutations of the 24 sticker positions.
// Generated by BFS from identity using {Rx, Ry, Rz} 90° as generators.
const ROTATIONS: ReadonlyArray<number[]> = (() => {
  const result: number[][] = [];
  const seen = new Set<string>();
  const identity: number[] = [];
  for (let i = 0; i < 24; i++) identity.push(i);
  result.push(identity);
  seen.add(identity.join(','));

  const generators = [
    buildWholeCubeRotation(1, 0, 0, -Math.PI / 2),
    buildWholeCubeRotation(0, 1, 0, -Math.PI / 2),
    buildWholeCubeRotation(0, 0, 1, -Math.PI / 2),
  ];

  let frontier = [identity];
  while (frontier.length > 0) {
    const next: number[][] = [];
    for (const r of frontier) {
      for (const g of generators) {
        const composed = new Array<number>(24);
        for (let i = 0; i < 24; i++) composed[i] = g[r[i]];
        const key = composed.join(',');
        if (!seen.has(key)) {
          seen.add(key);
          result.push(composed);
          next.push(composed);
        }
      }
    }
    frontier = next;
  }
  return result;
})();

// Hot path. Compare 24 rotated views of the state byte-by-byte against the current
// best, only materializing a new string when a smaller one is actually found.
const _canonStateBytes = new Uint8Array(24);
const _canonBestBytes = new Uint8Array(24);
function canonicalize(state: string): string {
  for (let i = 0; i < 24; i++) _canonStateBytes[i] = state.charCodeAt(i);
  for (let i = 0; i < 24; i++) _canonBestBytes[i] = _canonStateBytes[i];

  for (let r = 1; r < ROTATIONS.length; r++) {
    const perm = ROTATIONS[r];
    let cmp = 0;
    for (let j = 0; j < 24; j++) {
      const candidateByte = _canonStateBytes[perm[j]];
      const bestByte = _canonBestBytes[j];
      if (candidateByte < bestByte) {
        cmp = -1;
        break;
      }
      if (candidateByte > bestByte) {
        cmp = 1;
        break;
      }
    }
    if (cmp < 0) {
      for (let j = 0; j < 24; j++) _canonBestBytes[j] = _canonStateBytes[perm[j]];
    }
  }

  // Compose the result string once at the end.
  return String.fromCharCode(
    _canonBestBytes[0], _canonBestBytes[1], _canonBestBytes[2], _canonBestBytes[3],
    _canonBestBytes[4], _canonBestBytes[5], _canonBestBytes[6], _canonBestBytes[7],
    _canonBestBytes[8], _canonBestBytes[9], _canonBestBytes[10], _canonBestBytes[11],
    _canonBestBytes[12], _canonBestBytes[13], _canonBestBytes[14], _canonBestBytes[15],
    _canonBestBytes[16], _canonBestBytes[17], _canonBestBytes[18], _canonBestBytes[19],
    _canonBestBytes[20], _canonBestBytes[21], _canonBestBytes[22], _canonBestBytes[23],
  );
}

const MOVES: ReadonlyArray<MoveDef> = (() => {
  const list: MoveDef[] = [];
  for (const face of FACES) {
    const base = buildBaseFacePermutation(face);
    const double = composePerms(base, base);
    const inverse = composePerms(base, double);
    list.push({ name: face, perm: base });
    list.push({ name: `${face}2`, perm: double });
    list.push({ name: `${face}'`, perm: inverse });
  }
  return list;
})();

// In canonical space (modulo whole-cube rotation) L ≡ R⁻¹, D ≡ U⁻¹, B ≡ F⁻¹, so
// {R, U, F} variants generate the same canonical orbit as all six faces. We use
// this restricted move set in the BFS for a ~2× branching reduction. (The next-step
// cubes shown to the user will therefore only be R/U/F variants.)
const SEARCH_MOVES: ReadonlyArray<MoveDef> = MOVES.filter(
  (m) => m.name[0] === 'R' || m.name[0] === 'U' || m.name[0] === 'F',
);

// Face label per SEARCH_MOVES index, used for same-face pruning in BFS:
// two consecutive moves on the same face always compose to a single move on
// that face (or identity), so optimal paths never repeat a face.
const SEARCH_MOVE_FACE: ReadonlyArray<Face> = SEARCH_MOVES.map((m) => m.name[0] as Face);

function faceletsToString(facelets: CubeFacelets): string {
  let s = '';
  for (const face of FACES) {
    const arr = facelets[face];
    s += arr[0] + arr[1] + arr[2] + arr[3];
  }
  return s;
}

function stringToFacelets(s: string): CubeFacelets {
  const result = {} as CubeFacelets;
  for (let i = 0; i < FACES.length; i++) {
    const face = FACES[i];
    const o = i * 4;
    result[face] = [
      s[o] as Color,
      s[o + 1] as Color,
      s[o + 2] as Color,
      s[o + 3] as Color,
    ];
  }
  return result;
}

function applyPerm(state: string, perm: number[]): string {
  const chars = new Array<string>(24);
  for (let i = 0; i < 24; i++) chars[i] = state[perm[i]];
  return chars.join('');
}

function isSolved(state: string): boolean {
  for (let f = 0; f < 6; f++) {
    const base = f * 4;
    const c = state[base];
    if (state[base + 1] !== c || state[base + 2] !== c || state[base + 3] !== c) {
      return false;
    }
  }
  return true;
}

export interface SolveResult {
  steps: number;
  nextSteps: NextStepCube[];
}

export const MOVE_NAMES: ReadonlyArray<string> = MOVES.map((m) => m.name);
export const ROTATION_COUNT: number = ROTATIONS.length;

export function applyMove(facelets: CubeFacelets, moveName: string): CubeFacelets {
  const move = MOVES.find((m) => m.name === moveName);
  if (!move) throw new Error(`Unknown move: ${moveName}`);
  return stringToFacelets(applyPerm(faceletsToString(facelets), move.perm));
}

// Exhaustive BFS from `initial` using all 18 face turn permutations.
// Returns the size of the orbit (number of distinct states reachable),
// capped at `max` if the exploration goes past it.
export function countReachableStates(
  initial: CubeFacelets,
  max: number = Number.POSITIVE_INFINITY,
): number {
  const start = faceletsToString(initial);
  const visited = new Set<string>([start]);
  const queue: string[] = [start];
  let qi = 0;
  while (qi < queue.length) {
    if (visited.size > max) return visited.size;
    const s = queue[qi++];
    for (let mi = 0; mi < MOVES.length; mi++) {
      const next = applyPerm(s, MOVES[mi].perm);
      if (!visited.has(next)) {
        visited.add(next);
        queue.push(next);
      }
    }
  }
  return visited.size;
}

export function solveCube(facelets: CubeFacelets): SolveResult {
  const initialRaw = faceletsToString(facelets);
  if (isSolved(initialRaw)) {
    return { steps: 0, nextSteps: [] };
  }

  // BFS happens in canonical space — states are deduplicated modulo the 24 whole-cube
  // rotations. This collapses the 88M raw-sticker-arrangement orbit down to the
  // 3,674,160 canonical states (one per Pocket Cube position) so a single V8 Map
  // (cap 2^24) can hold the whole exploration.
  const initialCanon = canonicalize(initialRaw);
  const solvedCanon = canonicalize(faceletsToString(solvedCube()));
  if (initialCanon === solvedCanon) {
    // Already solved up to whole-cube rotation.
    return { steps: 0, nextSteps: [] };
  }

  // Forward BFS over canonical states, tracking depth + every parent at the same depth.
  // Parent list captures all equally-short paths so we can enumerate every optimal first move.
  // `lastFace` is the face of the move that first reached this state; used to prune
  // consecutive same-face moves during expansion.
  interface CanonInfo {
    depth: number;
    parents: Array<[string, number]>; // [parentCanonical, moveIdx in SEARCH_MOVES]
    lastFace: Face | null;
  }
  const fwdMap = new Map<string, CanonInfo>();
  fwdMap.set(initialCanon, { depth: 0, parents: [], lastFace: null });
  const queue: string[] = [initialCanon];
  let qi = 0;
  let solvedDepth = -1;

  const MAX_CANON_STATES = 4_000_000;

  while (qi < queue.length) {
    if (fwdMap.size > MAX_CANON_STATES) {
      console.warn(
        `[solver] canonical state explosion: ${fwdMap.size} states; aborting. ` +
          `Initial: ${initialRaw}`,
      );
      return { steps: -1, nextSteps: [] };
    }
    const s = queue[qi++];
    const info = fwdMap.get(s)!;
    if (solvedDepth >= 0 && info.depth >= solvedDepth) break;

    for (let mi = 0; mi < SEARCH_MOVES.length; mi++) {
      const moveFace = SEARCH_MOVE_FACE[mi];
      if (moveFace === info.lastFace) continue;
      const nextRaw = applyPerm(s, SEARCH_MOVES[mi].perm);
      const nextCanon = canonicalize(nextRaw);
      const existing = fwdMap.get(nextCanon);
      const nd = info.depth + 1;
      if (!existing) {
        fwdMap.set(nextCanon, { depth: nd, parents: [[s, mi]], lastFace: moveFace });
        if (nextCanon === solvedCanon) {
          if (solvedDepth < 0) solvedDepth = nd;
        } else {
          queue.push(nextCanon);
        }
      } else if (existing.depth === nd) {
        existing.parents.push([s, mi]);
      }
    }
  }

  if (solvedDepth < 0) {
    return { steps: -1, nextSteps: [] };
  }

  // Walk backward through parent layers to collect every canonical state at depth 1
  // that sits on some optimal path.
  let layer: Set<string> = new Set([solvedCanon]);
  for (let d = solvedDepth; d > 1; d--) {
    const prev = new Set<string>();
    for (const s of layer) {
      const info = fwdMap.get(s);
      if (info) for (const [p] of info.parents) prev.add(p);
    }
    layer = prev;
  }

  // A first move m is optimal iff canonicalize(initialRaw after m) is in `layer`.
  const firstMoves = new Set<number>();
  for (let mi = 0; mi < SEARCH_MOVES.length; mi++) {
    const child = applyPerm(initialRaw, SEARCH_MOVES[mi].perm);
    const childCanon = canonicalize(child);
    if (layer.has(childCanon)) firstMoves.add(mi);
  }

  const nextSteps: NextStepCube[] = [];
  for (const mi of firstMoves) {
    const move = SEARCH_MOVES[mi];
    nextSteps.push({
      facelets: stringToFacelets(applyPerm(initialRaw, move.perm)),
      instruction: move.name,
    });
  }
  return { steps: solvedDepth, nextSteps };
}
